### ISSUE TITLE
UnboundLocalError: local variable 'p' referenced before assignment

### ISSUE THREAD

**Issue by Ste97H02B** [benhackbarth/audioguide#16]
hi, I'm using audioguide 1.76 on M3 machine running os 13.6.3 and executing the package inside a virtual env with python 3.8.18. when typing: python agSegmentSf.py examples/lachenmann.aiff
I get the following error:
"/Users/stefano/Documents/audioguide-1.76/audioguide/ircamdescriptor-2.8.6/ircamdescriptor-2.8.6 /Users/stefano/Documents/audioguide-1.76/examples/lachenmann.aiff /Users/stefano/Documents/audioguide-1.76/audioguide/data/ircamdescriptor.config.txt"
Traceback (most recent call last):
  File "agSegmentSf.py", line 57, in <module>
    ag.load_target()
  File "/Users/stefano/Documents/audioguide-1.76/audioguide/_init_.py", line 84, in load_target
    self.tgt.initAnal(self.AnalInterface, self.ops, self.p)
  File "/Users/stefano/Documents/audioguide-1.76/audioguide/sfsegment.py", line 255, in initAnal
    self.whole = sfsegment(self.filename, self.startSec, self.endSec, AnalInterface, envDb=self.envDb, normtag='tgtwhole')
  File "/Users/stefano/Documents/audioguide-1.76/audioguide/sfsegment.py", line 24, in _init_
    self.soundfileTotalDuration, self.soundfileChns = AnalInterface.validateAnalResource(self.filename)
  File "/Users/stefano/Documents/audioguide-1.76/audioguide/anallinkage.py", line 313, in validateAnalResource
    self.initAnalResource(sffile)
  File "/Users/stefano/Documents/audioguide-1.76/audioguide/anallinkage.py", line 360, in initAnalResource
    self.rawData[sffile]['info'], self.rawData[sffile]['ircamd'] = self._createDescriptorsFile_(sffile, self.analdir, descriptorfile, infofile, self.ircamdescriptor_bin, self.config_loc)
  File "/Users/stefano/Documents/audioguide-1.76/audioguide/anallinkage.py", line 250, in _createDescriptorsFile_
    out, err = p.communicate()
UnboundLocalError: local variable 'p' referenced before assignment
any suggestions? thanks

**Comment by benhackbarth** [comment]
Have you tried it outside the virtual env, e.g. at the command line?

**Comment by Ste97H02B** [comment]
Hi, i’ve tried both inside and outside the environment and nothing changedInviato da iPhoneIl giorno 2 feb 2024, alle ore 18:39, benhackbarth ***@***.***> ha scritto:﻿
Have you tried it outside the virtual env, e.g. at the command line?
