### ISSUE TITLE
-i flag issue

### ISSUE THREAD

**Issue by nadirB** [benhackbarth/audioguide#9]
I was happily enjoying your beatboxing example 02-bowl.py in interactive mode while tweaking some params until : 

```
Traceback (most recent call last):
  File "agConcatenate.py", line 44, in <module>
    ag.execute()

  File "/Users/hecceite/Music/audioguide-1.74/audioguide/__init__.py", line 65, in execute
    self.standard_concatenate()
  File "/Users/hecceite/Music/audioguide-1.74/audioguide/__init__.py", line 188, in standard_concatenate
    self.instruments = musicalwriting.instruments(self.ops.INSTRUMENTS, self.ops.CORPUS, self.tgt.segs, self.tgt.leng
thInFrames, self.cps.postLimitSegmentNormList, self.AnalInterface.hopLengthSec, self.p)
  File "/Users/hecceite/Music/audioguide-1.74/audioguide/fileoutput/musicalwriting.py", line 243, in __init__
    self.setup_internalshit(scoreFromUserOptions, usercorpus, tgtsegs, tgtlength, cpsseglist, hopsizesec, p)
  File "/Users/hecceite/Music/audioguide-1.74/audioguide/fileoutput/musicalwriting.py", line 264, in setup_internalsh
it
    cpsids = [c.voiceID for c in usercorpus if c.instrTag in self.instruments[k]['cpsTags']]
AttributeError: 'CorpusOptionsEntry' object has no attribute 'voiceID'
```

The question is whether all the keywords fields are included in the interactive mode or not ? 
Because, for instance, the issue happens when the minspeed keyword is changed  and it does not occur while tweaking the CSOUND_PLAY_RENDERED_FILE bool... ?

**Comment by benhackbarth** [comment]
Thanks for this Nadir! I can confirm that there is a bug here. It looks like instruments are not working with interactive mode at the moment. Will investigate.

**Comment by benhackbarth** [comment]
I think that I've fixed this. Could you download the latest git and test and let me know if it works for you now ? :)

**Comment by nadirB** [comment]
yes it is fine ! Thanks.
